name: fghjk
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.16.1 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_size_text: 3.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^1.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/fghjk/assets/images/5_26.png
    - packages/fghjk/assets/images/5_27.png
    - packages/fghjk/assets/images/5_28.png
    - packages/fghjk/assets/images/I16_32;5_26.png
    - packages/fghjk/assets/images/I16_32;5_27.png
    - packages/fghjk/assets/images/I16_32;5_28.png
    - packages/fghjk/assets/images/I16_36;5_26.png
    - packages/fghjk/assets/images/I16_36;5_27.png
    - packages/fghjk/assets/images/I16_36;5_28.png
    - packages/fghjk/assets/images/18_35.png
    - packages/fghjk/assets/images/18_36.png
    - packages/fghjk/assets/images/18_52.png
    - packages/fghjk/assets/images/18_58.png
    - packages/fghjk/assets/images/18_61.png
    - packages/fghjk/assets/images/18_68.png
    - packages/fghjk/assets/images/18_77.png
    - packages/fghjk/assets/images/18_80.png
    - packages/fghjk/assets/images/18_83.png
    - packages/fghjk/assets/images/18_87.png
    - packages/fghjk/assets/images/18_91.png
    - packages/fghjk/assets/images/18_94.png
    - packages/fghjk/assets/images/18_97.png
    - packages/fghjk/assets/images/18_101.png
    - packages/fghjk/assets/images/18_104.png
    - packages/fghjk/assets/images/18_107.png
    - packages/fghjk/assets/images/18_110.png
    - packages/fghjk/assets/images/18_113.png
    - packages/fghjk/assets/images/18_116.png
    - packages/fghjk/assets/images/18_119.png
    - packages/fghjk/assets/images/18_122.png
    - packages/fghjk/assets/images/18_125.png
    - packages/fghjk/assets/images/18_126.png
    - packages/fghjk/assets/images/18_127.png
    - packages/fghjk/assets/images/11_118.png
    - packages/fghjk/assets/images/2_84.png
    - packages/fghjk/assets/images/2_88.png
    - packages/fghjk/assets/images/5_3.png
    - packages/fghjk/assets/images/2_116.png
    - packages/fghjk/assets/images/5_4.png
    - packages/fghjk/assets/images/2_124.png
    - packages/fghjk/assets/images/2_127.png
    - packages/fghjk/assets/images/2_102.png
    - packages/fghjk/assets/images/2_132.png
    - packages/fghjk/assets/images/2_133.png
    - packages/fghjk/assets/images/2_140.png
    - packages/fghjk/assets/images/5_518.png
    - packages/fghjk/assets/images/5_519.png
    - packages/fghjk/assets/images/5_520.png
    - packages/fghjk/assets/images/5_522.png
    - packages/fghjk/assets/images/5_527.png
    - packages/fghjk/assets/images/5_530.png
    - packages/fghjk/assets/images/5_535.png
